In [48]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model  import LinearRegression
from statsmodels.tsa.stattools import adfuller
import wbgapi as wb
import copy
pd.set_option("display.max_rows",None)
pd.set_option("display.max_columns",None)

In [2]:
region_all=wb.economy.info()

In [3]:
region_all.table()

[['ABW', 'Aruba', 'LCN', 'HIC'],
 ['AFE', 'Africa Eastern and Southern', '', ''],
 ['AFG', 'Afghanistan', 'SAS', 'LIC'],
 ['AFW', 'Africa Western and Central', '', ''],
 ['AGO', 'Angola', 'SSF', 'LMC'],
 ['ALB', 'Albania', 'ECS', 'UMC'],
 ['AND', 'Andorra', 'ECS', 'HIC'],
 ['ARB', 'Arab World', '', ''],
 ['ARE', 'United Arab Emirates', 'MEA', 'HIC'],
 ['ARG', 'Argentina', 'LCN', 'UMC'],
 ['ARM', 'Armenia', 'ECS', 'UMC'],
 ['ASM', 'American Samoa', 'EAS', 'UMC'],
 ['ATG', 'Antigua and Barbuda', 'LCN', 'HIC'],
 ['AUS', 'Australia', 'EAS', 'HIC'],
 ['AUT', 'Austria', 'ECS', 'HIC'],
 ['AZE', 'Azerbaijan', 'ECS', 'UMC'],
 ['BDI', 'Burundi', 'SSF', 'LIC'],
 ['BEL', 'Belgium', 'ECS', 'HIC'],
 ['BEN', 'Benin', 'SSF', 'LMC'],
 ['BFA', 'Burkina Faso', 'SSF', 'LIC'],
 ['BGD', 'Bangladesh', 'SAS', 'LMC'],
 ['BGR', 'Bulgaria', 'ECS', 'UMC'],
 ['BHR', 'Bahrain', 'MEA', 'HIC'],
 ['BHS', 'Bahamas, The', 'LCN', 'HIC'],
 ['BIH', 'Bosnia and Herzegovina', 'ECS', 'UMC'],
 ['BLR', 'Belarus', 'ECS', 'UMC'],

In [4]:
df0=pd.DataFrame(region_all.table(),columns=['iso','country','region','income_group'])
df0

iso                                            country region  \
0    ABW                                              Aruba    LCN   
1    AFE                        Africa Eastern and Southern          
2    AFG                                        Afghanistan    SAS   
3    AFW                         Africa Western and Central          
4    AGO                                             Angola    SSF   
5    ALB                                            Albania    ECS   
6    AND                                            Andorra    ECS   
7    ARB                                         Arab World          
8    ARE                               United Arab Emirates    MEA   
9    ARG                                          Argentina    LCN   
10   ARM                                            Armenia    ECS   
11   ASM                                     American Samoa    EAS   
12   ATG                                Antigua and Barbuda    LCN   
13   AUS                                          Australia    EAS   
14   AUT                                            Austria    ECS   
15   AZE                                         Azerbaijan    ECS   
16   BDI                                            Burundi    SSF   
17   BEL                                            Belgium    ECS   
18   BEN                                              Benin    SSF   
19   BFA                                       Burkina Faso    SSF   
20   BGD                                         Bangladesh    SAS   
21   BGR                                           Bulgaria    ECS   
22   BHR                                            Bahrain    MEA   
23   BHS                                       Bahamas, The    LCN   
24   BIH                             Bosnia and Herzegovina    ECS   
25   BLR                                            Belarus    ECS   
26   BLZ                                             Belize    LCN   
27   BMU                                            Bermuda    NAC   
28   BOL                                            Bolivia    LCN   
29   BRA                                             Brazil    LCN   
30   BRB                                           Barbados    LCN   
31   BRN                                  Brunei Darussalam    EAS   
32   BTN                                             Bhutan    SAS   
33   BWA                                           Botswana    SSF   
34   CAF                           Central African Republic    SSF   
35   CAN                                             Canada    NAC   
36   CEB                     Central Europe and the Baltics          
37   CHE                                        Switzerland    ECS   
38   CHI                                    Channel Islands    ECS   
39   CHL                                              Chile    LCN   
40   CHN                                              China    EAS   
41   CIV                                      Cote d'Ivoire    SSF   
42   CMR                                           Cameroon    SSF   
43   COD                                   Congo, Dem. Rep.    SSF   
44   COG                                        Congo, Rep.    SSF   
45   COL                                           Colombia    LCN   
46   COM                                            Comoros    SSF   
47   CPV                                         Cabo Verde    SSF   
48   CRI                                         Costa Rica    LCN   
49   CSS                             Caribbean small states          
50   CUB                                               Cuba    LCN   
51   CUW                                            Curacao    LCN   
52   CYM                                     Cayman Islands    LCN   
53   CYP                                             Cyprus    ECS   
54   CZE                                            Czechia    ECS   
55   DEU                                            Germany    ECS   
56   DJI       

In [5]:
dp=[]

for i in range(len(df0)):
    if not df0.iloc[i,2]:
        dp.append(i)

df1=df0.drop(dp).reset_index(drop=True).copy()
df1#regionを除いたデータフレーム

iso                         country region income_group
0    ABW                           Aruba    LCN          HIC
1    AFG                     Afghanistan    SAS          LIC
2    AGO                          Angola    SSF          LMC
3    ALB                         Albania    ECS          UMC
4    AND                         Andorra    ECS          HIC
5    ARE            United Arab Emirates    MEA          HIC
6    ARG                       Argentina    LCN          UMC
7    ARM                         Armenia    ECS          UMC
8    ASM                  American Samoa    EAS          UMC
9    ATG             Antigua and Barbuda    LCN          HIC
10   AUS                       Australia    EAS          HIC
11   AUT                         Austria    ECS          HIC
12   AZE                      Azerbaijan    ECS          UMC
13   BDI                         Burundi    SSF          LIC
14   BEL                         Belgium    ECS          HIC
15   BEN                           Benin    SSF          LMC
16   BFA                    Burkina Faso    SSF          LIC
17   BGD                      Bangladesh    SAS          LMC
18   BGR                        Bulgaria    ECS          UMC
19   BHR                         Bahrain    MEA          HIC
20   BHS                    Bahamas, The    LCN          HIC
21   BIH          Bosnia and Herzegovina    ECS          UMC
22   BLR                         Belarus    ECS          UMC
23   BLZ                          Belize    LCN          UMC
24   BMU                         Bermuda    NAC          HIC
25   BOL                         Bolivia    LCN          LMC
26   BRA                          Brazil    LCN          UMC
27   BRB                        Barbados    LCN          HIC
28   BRN               Brunei Darussalam    EAS          HIC
29   BTN                          Bhutan    SAS          LMC
30   BWA                        Botswana    SSF          UMC
31   CAF        Central African Republic    SSF          LIC
32   CAN                          Canada    NAC          HIC
33   CHE                     Switzerland    ECS          HIC
34   CHI                 Channel Islands    ECS          HIC
35   CHL                           Chile    LCN          HIC
36   CHN                           China    EAS          UMC
37   CIV                   Cote d'Ivoire    SSF          LMC
38   CMR                        Cameroon    SSF          LMC
39   COD                Congo, Dem. Rep.    SSF          LIC
40   COG                     Congo, Rep.    SSF          LMC
41   COL                        Colombia    LCN          UMC
42   COM                         Comoros    SSF          LMC
43   CPV                      Cabo Verde    SSF          LMC
44   CRI                      Costa Rica    LCN          UMC
45   CUB                            Cuba    LCN          UMC
46   CUW                         Curacao    LCN          HIC
47   CYM                  Cayman Islands    LCN          HIC
48   CYP                          Cyprus    ECS          HIC
49   CZE                         Czechia    ECS          HIC
50   DEU                         Germany    ECS          HIC
51   DJI                        Djibouti    MEA          LMC
52   DMA                        Dominica    LCN          UMC
53   DNK                         Denmark    ECS          HIC
54   DOM              Dominican Republic    LCN          UMC
55   DZA                         Algeria    MEA          LMC
56   ECU                         Ecuador    LCN          UMC
57   EGY                Egypt, Arab Rep.    MEA          LMC
58   ERI                         Eritrea    SSF          LIC
59   ESP                           Spain    ECS          HIC
60   EST                         Estonia    ECS          HIC
61   ETH                        Ethiopia    SSF          LIC
62   FIN                         Finland    ECS          HIC
63   FJI                            Fiji    EAS          UMC
64   FRA                          France

In [6]:
df2=df1.drop([0,7,24,34,40,46,47,52,65,71,80,88,118,119,133,140,157,161,162,184,187,207,208])

In [7]:
df2#島などを除いた純粋な独立国からなるデータフレーム

iso                         country region income_group
1    AFG                     Afghanistan    SAS          LIC
2    AGO                          Angola    SSF          LMC
3    ALB                         Albania    ECS          UMC
4    AND                         Andorra    ECS          HIC
5    ARE            United Arab Emirates    MEA          HIC
6    ARG                       Argentina    LCN          UMC
8    ASM                  American Samoa    EAS          UMC
9    ATG             Antigua and Barbuda    LCN          HIC
10   AUS                       Australia    EAS          HIC
11   AUT                         Austria    ECS          HIC
12   AZE                      Azerbaijan    ECS          UMC
13   BDI                         Burundi    SSF          LIC
14   BEL                         Belgium    ECS          HIC
15   BEN                           Benin    SSF          LMC
16   BFA                    Burkina Faso    SSF          LIC
17   BGD                      Bangladesh    SAS          LMC
18   BGR                        Bulgaria    ECS          UMC
19   BHR                         Bahrain    MEA          HIC
20   BHS                    Bahamas, The    LCN          HIC
21   BIH          Bosnia and Herzegovina    ECS          UMC
22   BLR                         Belarus    ECS          UMC
23   BLZ                          Belize    LCN          UMC
25   BOL                         Bolivia    LCN          LMC
26   BRA                          Brazil    LCN          UMC
27   BRB                        Barbados    LCN          HIC
28   BRN               Brunei Darussalam    EAS          HIC
29   BTN                          Bhutan    SAS          LMC
30   BWA                        Botswana    SSF          UMC
31   CAF        Central African Republic    SSF          LIC
32   CAN                          Canada    NAC          HIC
33   CHE                     Switzerland    ECS          HIC
35   CHL                           Chile    LCN          HIC
36   CHN                           China    EAS          UMC
37   CIV                   Cote d'Ivoire    SSF          LMC
38   CMR                        Cameroon    SSF          LMC
39   COD                Congo, Dem. Rep.    SSF          LIC
41   COL                        Colombia    LCN          UMC
42   COM                         Comoros    SSF          LMC
43   CPV                      Cabo Verde    SSF          LMC
44   CRI                      Costa Rica    LCN          UMC
45   CUB                            Cuba    LCN          UMC
48   CYP                          Cyprus    ECS          HIC
49   CZE                         Czechia    ECS          HIC
50   DEU                         Germany    ECS          HIC
51   DJI                        Djibouti    MEA          LMC
53   DNK                         Denmark    ECS          HIC
54   DOM              Dominican Republic    LCN          UMC
55   DZA                         Algeria    MEA          LMC
56   ECU                         Ecuador    LCN          UMC
57   EGY                Egypt, Arab Rep.    MEA          LMC
58   ERI                         Eritrea    SSF          LIC
59   ESP                           Spain    ECS          HIC
60   EST                         Estonia    ECS          HIC
61   ETH                        Ethiopia    SSF          LIC
62   FIN                         Finland    ECS          HIC
63   FJI                            Fiji    EAS          UMC
64   FRA                          France    ECS          HIC
66   FSM           Micronesia, Fed. Sts.    EAS          LMC
67   GAB                           Gabon    SSF          UMC
68   GBR                  United Kingdom    ECS          HIC
69   GEO                         Georgia    ECS          UMC
70   GHA                           Ghana    SSF          LMC
72   GIN                          Guinea    SSF          LIC
73   GMB                     Gambia, The    SSF          LIC
74   GNB                   Guinea-Bissau

In [8]:
df2.info()#194カ国

<class 'pandas.core.frame.DataFrame'>
Int64Index: 194 entries, 1 to 216
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   iso           194 non-null    object
 1   country       194 non-null    object
 2   region        194 non-null    object
 3   income_group  194 non-null    object
dtypes: object(4)
memory usage: 7.6+ KB


In [10]:
df3=df2.values[:,0]
df3#国名のみ抽出

array(['AFG', 'AGO', 'ALB', 'AND', 'ARE', 'ARG', 'ASM', 'ATG', 'AUS',
       'AUT', 'AZE', 'BDI', 'BEL', 'BEN', 'BFA', 'BGD', 'BGR', 'BHR',
       'BHS', 'BIH', 'BLR', 'BLZ', 'BOL', 'BRA', 'BRB', 'BRN', 'BTN',
       'BWA', 'CAF', 'CAN', 'CHE', 'CHL', 'CHN', 'CIV', 'CMR', 'COD',
       'COL', 'COM', 'CPV', 'CRI', 'CUB', 'CYP', 'CZE', 'DEU', 'DJI',
       'DNK', 'DOM', 'DZA', 'ECU', 'EGY', 'ERI', 'ESP', 'EST', 'ETH',
       'FIN', 'FJI', 'FRA', 'FSM', 'GAB', 'GBR', 'GEO', 'GHA', 'GIN',
       'GMB', 'GNB', 'GNQ', 'GRC', 'GRD', 'GRL', 'GTM', 'GUY', 'HKG',
       'HND', 'HRV', 'HTI', 'HUN', 'IDN', 'IND', 'IRL', 'IRN', 'IRQ',
       'ISL', 'ISR', 'ITA', 'JAM', 'JOR', 'JPN', 'KAZ', 'KEN', 'KGZ',
       'KHM', 'KIR', 'KNA', 'KOR', 'KWT', 'LAO', 'LBN', 'LBR', 'LBY',
       'LCA', 'LIE', 'LKA', 'LSO', 'LTU', 'LUX', 'LVA', 'MAR', 'MCO',
       'MDA', 'MDG', 'MDV', 'MEX', 'MHL', 'MKD', 'MLI', 'MLT', 'MMR',
       'MNE', 'MNG', 'MOZ', 'MRT', 'MUS', 'MWI', 'MYS', 'NAM', 'NER',
       'NGA', 'NIC',

In [11]:
df4=wb.data.DataFrame(["SL.TLF.ACTI.FE.ZS","SL.TLF.CACT.ZS","SP.POP.GROW","NE.CON.PRVT.PC.KD","SH.STA.SUIC.P5",
                      "SP.DYN.TFRT.IN","SE.ENR.PRIM.FM.ZS","SL.UEM.TOTL.NE.ZS",
                       "MS.MIL.XPND.CD","SH.H2O.SMDW.ZS","SP.DYN.AMRT.FE",
                       "SP.DYN.AMRT.MA","IT.NET.USER.ZS"],df3,mrv=5)
df4

YR2017        YR2018        YR2019  \
economy series                                                        
AFG     IT.NET.USER.ZS     1.350000e+01  1.680000e+01  1.760000e+01   
        MS.MIL.XPND.CD     1.914071e+08  1.980747e+08  2.258356e+08   
        NE.CON.PRVT.PC.KD           NaN           NaN           NaN   
        SE.ENR.PRIM.FM.ZS  6.761700e-01  6.669100e-01  6.716900e-01   
        SH.H2O.SMDW.ZS     2.508389e+01  2.594051e+01  2.679896e+01   
        SH.STA.SUIC.P5     4.100000e+00  4.100000e+00  4.100000e+00   
        SL.TLF.ACTI.FE.ZS  2.191000e+01  2.232000e+01  2.274000e+01   
        SL.TLF.CACT.ZS     4.731000e+01  4.737600e+01  4.744000e+01   
        SL.UEM.TOTL.NE.ZS  1.118000e+01           NaN           NaN   
        SP.DYN.AMRT.FE     1.981840e+02  1.925320e+02  1.888390e+02   
        SP.DYN.AMRT.MA     2.403140e+02  2.375540e+02  2.338840e+02   
        SP.DYN.TFRT.IN     4.633000e+00  4.473000e+00  4.321000e+00   
        SP.POP.GROW        2.547833e+00  2.384309e+00  2.313073e+00   
AGO     IT.NET.USER.ZS     2.600000e+01  2.900000e+01  3.240000e+01   
        MS.MIL.XPND.CD     3.062873e+09  1.983614e+09  1.470939e+09   
        NE.CON.PRVT.PC.KD  1.681170e+03  1.571456e+03  1.427415e+03   
        SE.ENR.PRIM.FM.ZS           NaN           NaN           NaN   
        SH.H2O.SMDW.ZS              NaN           NaN           NaN   
        SH.STA.SUIC.P5     6.000000e+00  6.000000e+00  6.100000e+00   
        SL.TLF.ACTI.FE.ZS  7.691000e+01  7.690000e+01  7.688000e+01   
        SL.TLF.CACT.ZS     7.728100e+01  7.725100e+01  7.721300e+01   
        SL.UEM.TOTL.NE.ZS           NaN           NaN           NaN   
        SP.DYN.AMRT.FE     1.999810e+02  2.202910e+02  2.168210e+02   
        SP.DYN.AMRT.MA     2.734350e+02  3.270440e+02  3.230910e+02   
        SP.DYN.TFRT.IN     5.600000e+00  5.519000e+00  5.442000e+00   
        SP.POP.GROW        3.322158e+00  3.276145e+00  3.242914e+00   
ALB     IT.NET.USER.ZS     6.240000e+01  6.540000e+01  6.855039e+01   
        MS.MIL.XPND.CD     1.443827e+08  1.758867e+08  1.972259e+08   
        NE.CON.PRVT.PC.KD  3.345555e+03  3.461663e+03  3.553792e+03   
        SE.ENR.PRIM.FM.ZS  1.032240e+00  1.037650e+00  1.029630e+00   
        SH.H2O.SMDW.ZS     7.063694e+01  7.065335e+01  7.066585e+01   
        SH.STA.SUIC.P5     4.700000e+00  4.500000e+00  4.300000e+00   
        SL.TLF.ACTI.FE.ZS  5.554000e+01  5.912000e+01  6.146000e+01   
        SL.TLF.CACT.ZS     5.806000e+01  5.930000e+01  6.031000e+01   
        SL.UEM.TOTL.NE.ZS  1.362000e+01  1.230000e+01  1.147000e+01   
        SP.DYN.AMRT.FE     4.988400e+01  4.948600e+01  4.908800e+01   
        SP.DYN.AMRT.MA     9.445000e+01  9.331500e+01  9.217900e+01   
        SP.DYN.TFRT.IN     1.638000e+00  1.617000e+00  1.597000e+00   
        SP.POP.GROW       -9.197229e-02 -2.467320e-01 -4.260074e-01   
AND     IT.NET.USER.ZS     9.156747e+01           NaN           NaN   
        MS.MIL.XPND.CD              NaN           NaN           NaN   
        NE.CON.PRVT.PC.KD           NaN           NaN           NaN   
        SE.ENR.PRIM.FM.ZS           NaN           NaN           NaN   
        SH.H2O.SMDW.ZS     9.064000e+01  9.064000e+01  9.064000e+01   
        SH.STA.SUIC.P5              NaN           NaN           NaN   
        SL.TLF.ACTI.FE.ZS           NaN           NaN           NaN   
        SL.TLF.CACT.ZS              NaN           NaN           NaN   
        SL.UEM.TOTL.NE.ZS           NaN           NaN           NaN   
        SP.DYN.AMRT.FE              NaN           NaN           NaN   
        SP.DYN.AMRT.MA              NaN           NaN           NaN   
        SP.DYN.TFRT.IN              NaN           NaN           NaN   
        SP.POP.GROW       -3.862810e-01  1.428525e-02  1.790418e-01   
ARE     IT.NET.USER.ZS     9.481992e+01  9.845000e+01  9.915000e+01   
        MS.MIL.XPND.CD              NaN           NaN           NaN   
        NE.CON.PRVT.PC.KD  1.486039e+04  1.553134e+04  1.

In [14]:
d1=wb.data.DataFrame(["NY.GDP.PCAP.CD","SL.TLF.ACTI.FE.ZS","SL.TLF.CACT.ZS","SP.POP.GROW","NE.CON.PRVT.PC.KD","SH.STA.SUIC.P5",
                      "SP.DYN.TFRT.IN","SE.ENR.PRIM.FM.ZS","SL.UEM.TOTL.NE.ZS","EN.POP.DNST",
                       "MS.MIL.XPND.CD","SH.H2O.SMDW.ZS","SP.DYN.AMRT.FE",
                       "SP.DYN.AMRT.MA","IT.NET.USER.ZS","AG.LND.AGRI.K2","SH.DYN.NCOM.ZS",
                     "DT.DOD.DECT.CD","BM.KLT.DINV.CD.WD","GB.XPD.RSDV.GD.ZS"],df3,time="2019")

d2=wb.data.DataFrame(["NY.GDP.PCAP.CD","SL.TLF.ACTI.FE.ZS","SL.TLF.CACT.ZS","SP.POP.GROW","NE.CON.PRVT.PC.KD","SH.STA.SUIC.P5",
                      "SP.DYN.TFRT.IN","SE.ENR.PRIM.FM.ZS","SL.UEM.TOTL.NE.ZS","EN.POP.DNST",
                       "MS.MIL.XPND.CD","SH.H2O.SMDW.ZS","SP.DYN.AMRT.FE",
                       "SP.DYN.AMRT.MA","IT.NET.USER.ZS","AG.LND.AGRI.K2","SH.DYN.NCOM.ZS",
                     "DT.DOD.DECT.CD","BM.KLT.DINV.CD.WD","GB.XPD.RSDV.GD.ZS"],df3,time="2018")

d3=wb.data.DataFrame(["NY.GDP.PCAP.CD","SL.TLF.ACTI.FE.ZS","SL.TLF.CACT.ZS","SP.POP.GROW","NE.CON.PRVT.PC.KD","SH.STA.SUIC.P5",
                      "SP.DYN.TFRT.IN","SE.ENR.PRIM.FM.ZS","SL.UEM.TOTL.NE.ZS","EN.POP.DNST",
                       "MS.MIL.XPND.CD","SH.H2O.SMDW.ZS","SP.DYN.AMRT.FE",
                       "SP.DYN.AMRT.MA","IT.NET.USER.ZS","AG.LND.AGRI.K2","SH.DYN.NCOM.ZS",
                     "DT.DOD.DECT.CD","BM.KLT.DINV.CD.WD","GB.XPD.RSDV.GD.ZS"],df3,time="2017")

d4=wb.data.DataFrame(["NY.GDP.PCAP.CD","SL.TLF.ACTI.FE.ZS","SL.TLF.CACT.ZS","SP.POP.GROW","NE.CON.PRVT.PC.KD","SH.STA.SUIC.P5",
                      "SP.DYN.TFRT.IN","SE.ENR.PRIM.FM.ZS","SL.UEM.TOTL.NE.ZS","EN.POP.DNST",
                       "MS.MIL.XPND.CD","SH.H2O.SMDW.ZS","SP.DYN.AMRT.FE",
                       "SP.DYN.AMRT.MA","IT.NET.USER.ZS","AG.LND.AGRI.K2","SH.DYN.NCOM.ZS",
                     "DT.DOD.DECT.CD","BM.KLT.DINV.CD.WD","GB.XPD.RSDV.GD.ZS"],df3,time="2016")

d5=wb.data.DataFrame(["NY.GDP.PCAP.CD","SL.TLF.ACTI.FE.ZS","SL.TLF.CACT.ZS","SP.POP.GROW","NE.CON.PRVT.PC.KD","SH.STA.SUIC.P5",
                      "SP.DYN.TFRT.IN","SE.ENR.PRIM.FM.ZS","SL.UEM.TOTL.NE.ZS","EN.POP.DNST",
                       "MS.MIL.XPND.CD","SH.H2O.SMDW.ZS","SP.DYN.AMRT.FE",
                       "SP.DYN.AMRT.MA","IT.NET.USER.ZS","AG.LND.AGRI.K2","SH.DYN.NCOM.ZS",
                     "DT.DOD.DECT.CD","BM.KLT.DINV.CD.WD","GB.XPD.RSDV.GD.ZS"],df3,time="2015")

d6=wb.data.DataFrame(["NY.GDP.PCAP.CD","SL.TLF.ACTI.FE.ZS","SL.TLF.CACT.ZS","SP.POP.GROW","NE.CON.PRVT.PC.KD","SH.STA.SUIC.P5",
                      "SP.DYN.TFRT.IN","SE.ENR.PRIM.FM.ZS","SL.UEM.TOTL.NE.ZS","EN.POP.DNST",
                       "MS.MIL.XPND.CD","SH.H2O.SMDW.ZS","SP.DYN.AMRT.FE",
                       "SP.DYN.AMRT.MA","IT.NET.USER.ZS","AG.LND.AGRI.K2","SH.DYN.NCOM.ZS",
                     "DT.DOD.DECT.CD","BM.KLT.DINV.CD.WD","GB.XPD.RSDV.GD.ZS"],df3,time="2014")

d7=wb.data.DataFrame(["NY.GDP.PCAP.CD","SL.TLF.ACTI.FE.ZS","SL.TLF.CACT.ZS","SP.POP.GROW","NE.CON.PRVT.PC.KD","SH.STA.SUIC.P5",
                      "SP.DYN.TFRT.IN","SE.ENR.PRIM.FM.ZS","SL.UEM.TOTL.NE.ZS","EN.POP.DNST",
                       "MS.MIL.XPND.CD","SH.H2O.SMDW.ZS","SP.DYN.AMRT.FE",
                       "SP.DYN.AMRT.MA","IT.NET.USER.ZS","AG.LND.AGRI.K2","SH.DYN.NCOM.ZS",
                     "DT.DOD.DECT.CD","BM.KLT.DINV.CD.WD","GB.XPD.RSDV.GD.ZS"],df3,time="2013")

d8=wb.data.DataFrame(["NY.GDP.PCAP.CD","SL.TLF.ACTI.FE.ZS","SL.TLF.CACT.ZS","SP.POP.GROW","NE.CON.PRVT.PC.KD","SH.STA.SUIC.P5",
                      "SP.DYN.TFRT.IN","SE.ENR.PRIM.FM.ZS","SL.UEM.TOTL.NE.ZS","EN.POP.DNST",
                       "MS.MIL.XPND.CD","SH.H2O.SMDW.ZS","SP.DYN.AMRT.FE",
                       "SP.DYN.AMRT.MA","IT.NET.USER.ZS","AG.LND.AGRI.K2","SH.DYN.NCOM.ZS",
                     "DT.DOD.DECT.CD","BM.KLT.DINV.CD.WD","GB.XPD.RSDV.GD.ZS"],df3,time="2012")


d9=wb.data.DataFrame(["NY.GDP.PCAP.CD","SL.TLF.ACTI.FE.ZS","SL.TLF.CACT.ZS","SP.POP.GROW","NE.CON.PRVT.PC.KD","SH.STA.SUIC.P5",
                      "SP.DYN.TFRT.IN","SE.ENR.PRIM.FM.ZS","SL.UEM.TOTL.NE.ZS","EN.POP.DNST",
                       "MS.MIL.XPND.CD","SH.H2O.SMDW.ZS","SP.DYN.AMRT.FE",
                       "SP.DYN.AMRT.MA","IT.NET.USER.ZS","AG.LND.AGRI.K2","SH.DYN.NCOM.ZS",
                     "DT.DOD.DECT.CD","BM.KLT.DINV.CD.WD","GB.XPD.RSDV.GD.ZS"],df3,time="2011")

d10=wb.data.DataFrame(["NY.GDP.PCAP.CD","SL.TLF.ACTI.FE.ZS","SL.TLF.CACT.ZS","SP.POP.GROW","NE.CON.PRVT.PC.KD","SH.STA.SUIC.P5",
                      "SP.DYN.TFRT.IN","SE.ENR.PRIM.FM.ZS","SL.UEM.TOTL.NE.ZS","EN.POP.DNST",
                       "MS.MIL.XPND.CD","SH.H2O.SMDW.ZS","SP.DYN.AMRT.FE",
                       "SP.DYN.AMRT.MA","IT.NET.USER.ZS","AG.LND.AGRI.K2","SH.DYN.NCOM.ZS",
                     "DT.DOD.DECT.CD","BM.KLT.DINV.CD.WD","GB.XPD.RSDV.GD.ZS"],df3,time="2010")

d11=wb.data.DataFrame(["NY.GDP.PCAP.CD","SL.TLF.ACTI.FE.ZS","SL.TLF.CACT.ZS","SP.POP.GROW","NE.CON.PRVT.PC.KD","SH.STA.SUIC.P5",
                      "SP.DYN.TFRT.IN","SE.ENR.PRIM.FM.ZS","SL.UEM.TOTL.NE.ZS","EN.POP.DNST",
                       "MS.MIL.XPND.CD","SH.H2O.SMDW.ZS","SP.DYN.AMRT.FE",
                       "SP.DYN.AMRT.MA","IT.NET.USER.ZS","AG.LND.AGRI.K2","SH.DYN.NCOM.ZS",
                     "DT.DOD.DECT.CD","BM.KLT.DINV.CD.WD","GB.XPD.RSDV.GD.ZS"],df3,time="2009")



In [15]:
d_2019=d1.dropna()
d_2018=d2.dropna()
d_2017=d3.dropna()
d_2016=d4.dropna()
d_2015=d5.dropna()
d_2014=d6.dropna()
d_2013=d7.dropna()
d_2012=d8.dropna()
d_2011=d9.dropna()
d_2010=d10.dropna()
d_2009=d11.dropna()

In [73]:
df7=pd.concat([d_2017,d_2016,d_2015,d_2014,d_2013,d_2012,d_2011,d_2010,d_2009])
df10=pd.concat([d_2019,d_2018])
df11=pd.concat([d_2019,d_2018,d_2017,d_2016,d_2015,d_2014,d_2013,d_2012,d_2011,d_2010,d_2009])

In [55]:
df7
#使用する特徴量（説明変数）一覧
#[SL.TLF.ACTI.FE.ZS 女性の労働力率（15歳以上64歳以下の女性人口に占める割合）（ILOのモデル推計値）,
#SL.TLF.CACT.ZS 総労働力率（15歳以上の全人口に対する割合）（モデルILO推計値）,SP.POP.GROW 人口成長率（年率,EG.FEC.RNEW.ZS 再生可能エネルギー消費量（総最終エネルギー消費量に占める割合）
#NE.CON.PRVT.PC.KD 家計及びNPISHs 一人当たり最終消費支出（暫定2015年US,SH.DYN.NMRT 新生児死亡率（出生1,000人当たり）,SH.STA.SUIC.P5 自殺死亡率（人口10万人当たり）
#SP.DYN.TFRT.IN 合計特殊出生率（女性1人当たり出生数）ジェンダーパリティ指数（GPI)SE.ENR.PRIM.FM.ZS 就学率、初等教育（グロス）、ジェンダーパリティインデックス（GPI)
#SL.UEM.TOTL.NE.ZS 失業、合計（総労働力に対する割合）（国の推計値）,MS.MIL.XPND.CD 軍事費,SH.H2O.SMDW.ZS 安全に管理された飲料水サービスを利用している人（人口比）EG.ELC.RNEW.ZS 再生可能エネルギーによる発電量（総発電量に占める割合）
#SP.DYN.AMRT.FE 成人女性の死亡率（成人女性1,000人当たり）
#SP.DYN.AMRT.MA 男性成人の死亡率（男性成人1,000人当たり）,IT.NET.USER.ZS インターネットを利用する個人 (人口比)



AG.LND.AGRI.K2  BM.KLT.DINV.CD.WD  DT.DOD.DECT.CD  EN.POP.DNST  \
economy                                                                   
BGR           50295.200       4.957700e+08    4.098914e+10    65.180057   
BLR           84940.000       6.780000e+07    3.958422e+10    46.598760   
BRA         2368786.000       2.134051e+10    5.430003e+11    24.866038   
COL          494990.000       3.689564e+09    1.257691e+11    44.082780   
CRI           17795.000       2.728136e+08    2.561591e+10    96.943890   
GEO           23848.000       2.092824e+08    1.642392e+10    65.222786   
GTM           38560.000       6.432770e+07    2.326489e+10   150.125215   
IRN          464350.000       7.574844e+07    6.819094e+09    49.721965   
KAZ         2162137.000       9.565019e+08    1.589490e+11     6.681400   
KGZ          105401.000      -2.906890e+07    8.124568e+09    32.315954   
MDA           23173.000       1.087000e+07    6.968634e+09    95.908309   
MEX          969460.000       3.083417e+09    4.441526e+11    64.187518   
MKD           12660.000       1.822008e+08    8.544276e+09    82.256225   
MNE            2563.000       1.107288e+07    7.218787e+09    46.273086   
MNG         1134671.900       4.861424e+07    2.796318e+10     1.999536   
PER          245181.080       1.421518e+09    6.760358e+10    24.565859   
ROU          133780.000       3.863324e+08    1.140080e+11    85.138713   
SRB           34380.000       1.495063e+08    3.145393e+10    80.275074   
TUN           97430.000       5.745167e+07    3.350079e+10    73.593190   
BGR           50210.000       8.270200e+08    3.999403e+10    65.657903   
BLR           85327.000       1.229000e+08    3.751595e+10    46.649945   
BRA         2361590.000       1.469348e+10    5.432572e+11    24.666141   
CIV          212000.000       2.865143e+07    1.145719e+10    74.914233   
COL          447230.000       4.517352e+09    1.206585e+11    43.420503   
CRI           17775.000       4.934005e+08    2.556267e+10    95.952526   
GEO           23940.000       4.129995e+08    1.632011e+10    65.214056   
GTM           38560.000      -1.192368e+08    2.112983e+10   147.701474   
JOR           10659.600       3.239437e+06    2.711047e+10   107.617549   
KAZ         2162421.000       3.474581e+09    1.634885e+11     6.591123   
KGZ          105411.000       4.025190e+07    7.972110e+09    31.697080   
MDA           23179.000       1.333000e+07    6.222242e+09    97.578786   
MEX          983380.000       7.869653e+09    4.242681e+11    63.444728   
MNE            2557.000      -1.848736e+08    6.220224e+09    46.267881   
MNG         1135607.900       1.447297e+07    2.461208e+10     1.962657   
PER          244430.000       1.526241e+09    6.961278e+10    24.160966   
ROU          135210.000       1.255764e+09    9.611794e+10    85.632245   
SRB           34560.000       2.523834e+08    2.832680e+10    80.703430   
TUN           97030.000       2.416167e+08    2.882733e+10    72.759668   
AZE           47698.000       3.209378e+09    1.331882e+10   116.731077   
BGR           50119.000       1.232200e+08    4.037860e+10    66.120035   
BLR           85742.000       1.066000e+08    3.825792e+10    46.611337   
BRA         2354382.000       3.133977e+09    5.433974e+11    24.463787   
COL          447539.000       4.217736e+09    1.133634e+11    42.830705   
CRI           17775.000       4.142127e+08    2.358878e+10    94.943302   
GEO           24181.000       3.156997e+08    1.487462e+10    65.175059   
GTM           38560.000       1.552630e+08    2.037822e+10   145.272667   
IRN          459540.000       1.196910e+08    6.455859e+09    48.191390   
KAZ         2162597.000       3.316377e+09    1.531796e+11     6.498058   
KGZ          105562.000       1.349600e+08    7.720317e+09    31.057873   
KHM           55820.000       8.776104e+07    9.436048e+09    87.930178   
MDA           23180.000       7.310000e+06    6.094647e+09    98.705645   
MEX          986800.000       1.09

In [56]:
df7.info()

<class 'pandas.core.frame.DataFrame'>
Index: 175 entries, BGR to UKR
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   AG.LND.AGRI.K2     175 non-null    float64
 1   BM.KLT.DINV.CD.WD  175 non-null    float64
 2   DT.DOD.DECT.CD     175 non-null    float64
 3   EN.POP.DNST        175 non-null    float64
 4   GB.XPD.RSDV.GD.ZS  175 non-null    float64
 5   IT.NET.USER.ZS     175 non-null    float64
 6   MS.MIL.XPND.CD     175 non-null    float64
 7   NE.CON.PRVT.PC.KD  175 non-null    float64
 8   NY.GDP.PCAP.CD     175 non-null    float64
 9   SE.ENR.PRIM.FM.ZS  175 non-null    float64
 10  SH.DYN.NCOM.ZS     175 non-null    float64
 11  SH.H2O.SMDW.ZS     175 non-null    float64
 12  SH.STA.SUIC.P5     175 non-null    float64
 13  SL.TLF.ACTI.FE.ZS  175 non-null    float64
 14  SL.TLF.CACT.ZS     175 non-null    float64
 15  SL.UEM.TOTL.NE.ZS  175 non-null    float64
 16  SP.DYN.AMRT.FE     175 non-nu

In [60]:
#target_data=df7.loc[:,"NY.GDP.PCAP.CD"]
#target_dataes=target_data.values.reshape(-1,1)

#訓練データ(2009~2017)
train_dataY=df7.loc[:,"NY.GDP.PCAP.CD"]
train_y=train_dataY.values.reshape(-1,1)

#テストデータ
test_dataY=df10.loc[:,"NY.GDP.PCAP.CD"]
test_y=test_dataY.values.reshape(-1,1)

In [61]:
#data_set=df7.drop("NY.GDP.PCAP.CD",axis=1)
#data_sets=data_set.values
#data_sets

#訓練データ
train_dataX=df7.drop("NY.GDP.PCAP.CD",axis=1)
train_x=train_dataX.values

#テストデータ
test_dataX=df10.drop("NY.GDP.PCAP.CD",axis=1)
test_x=test_dataX.values

In [63]:
#各特徴量と説明変数が取る値が0~1の範囲になる様に正規化
from sklearn.preprocessing import MinMaxScaler
minmax_sc=MinMaxScaler()
x_tr=train_x
y_tr=train_y

x_test=test_x
y_test=test_y

x_tr=minmax_sc.fit_transform(x_tr)
y_tr=minmax_sc.fit_transform(y_tr)
x_test=minmax_sc.fit_transform(x_test)
y_test=minmax_sc.fit_transform(y_test)
#x=minmax_sc.fit_transform(x)
#y=minmax_sc.fit_transform(y)
#print(x)
#print(y)


In [22]:
#x_train,x_test,y_train,y_test=train_test_split(x,y)

In [23]:
#reg_rbf=SVR(kernel="rbf",C=1,epsilon=0.1,gamma="auto")
#reg_rbf.fit(x_train,y_train)

/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVR(C=1, gamma='auto')

In [24]:
#reg_rbf.score(x_test,y_test)#データセットの分割の仕方によってスコアが変動するため交差検証法を使う

0.8673671582882727

In [64]:
#train dataを訓練、検証セットに分割
#x_trainval,x_test,y_trainval,y_test=train_test_split(x,y)
x_train,x_valid,y_train,y_valid=train_test_split(x_tr,y_tr)

In [70]:
#交差検証法を用いたグリッドサーチ
best_score=0
best_parameters={}

param_list=[0.001,0.01,0.1,1,10,100]

for gamma in param_list:
    for C in param_list:
        for epsilon in param_list:
            svr=SVR(kernel="rbf",C=C,epsilon=epsilon,gamma=gamma)
            scores=cross_val_score(svr,x_tr,y_tr,cv=5)
            score=np.mean(scores)
            
            if score > best_score:
                best_score=score
                best_parameters={"gamma":gamma,"C":C,"epsilon":epsilon}

svr=SVR(**best_parameters)
svr.fit(x_tr,y_tr)
test_score=svr.score(x_test,y_test)



/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when

/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when

/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when

/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when

/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when

/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when

/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when

/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when

/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when

In [72]:
print(test_score)
print(best_parameters)


0.739342106796608
{'gamma': 1, 'C': 10, 'epsilon': 0.01}


In [28]:
#各特徴量の平均を求める関数を作る
mean_list=[]
def meanf(a):
    for i in range(19):
        b=a[:,i]
        c=np.mean(b)
        mean_list.append(c)
    return mean_list
    

In [29]:

def Sensf(a,b):
    Sensitive_list=[]
    for i in range(19):
        df0=a.drop(a.columns[i],axis="columns")
        
        df0.insert(i,b.columns[i],b.iloc[:,i])
        print(df0)
        data=df0.values
        print(data)
        svr_out=svr.predict(data)#生成したモデルに基づいて予測
        reg = LinearRegression().fit(b.iloc[:,i],svr_out)
        reg.coef_[i]
        Sensitive_list.append(reg.coef_[i])
        
    return Sensitive_list
    

In [89]:
x_values=df11.drop("NY.GDP.PCAP.CD",axis=1).values
x_values=minmax_sc.fit_transform(x_values)
x_values

array([[1.        , 0.30126325, 0.85045903, ..., 0.31673556, 0.09259259,
        0.50283038],
       [0.20865473, 0.08549789, 0.20654752, ..., 0.20625836, 0.10668277,
        0.62737865],
       [0.00904806, 0.05432133, 0.02705679, ..., 0.41767781, 0.16022544,
        0.31286753],
       ...,
       [0.04038751, 0.05174455, 0.03327838, ..., 0.12948936, 0.16827697,
        0.56686339],
       [0.05866787, 0.05121605, 0.00310772, ..., 0.98123708, 1.        ,
        1.        ],
       [0.17344201, 0.05216123, 0.15665463, ..., 0.76596353, 0.04307568,
        0.25683751]])

In [30]:
meanf(x)

[0.20751274913607134,
 0.08552420187258936,
 0.14169898559258015,
 0.13254239596390713,
 0.30034849332921804,
 0.5596704712643792,
 0.061591551205278115,
 0.4378254155402604,
 0.5565524599048634,
 0.3601674641148326,
 0.6828923964116737,
 0.2873977873977874,
 0.5377285128194529,
 0.4208988863621483,
 0.2616949427749984,
 0.15356974784213306,
 0.3531083753872107,
 0.1933118369045143,
 0.5233753951870519]

In [74]:
df8=copy.copy(df11)

In [77]:
df11.info()

<class 'pandas.core.frame.DataFrame'>
Index: 209 entries, BRA to UKR
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   AG.LND.AGRI.K2     209 non-null    float64
 1   BM.KLT.DINV.CD.WD  209 non-null    float64
 2   DT.DOD.DECT.CD     209 non-null    float64
 3   EN.POP.DNST        209 non-null    float64
 4   GB.XPD.RSDV.GD.ZS  209 non-null    float64
 5   IT.NET.USER.ZS     209 non-null    float64
 6   MS.MIL.XPND.CD     209 non-null    float64
 7   NE.CON.PRVT.PC.KD  209 non-null    float64
 8   NY.GDP.PCAP.CD     209 non-null    float64
 9   SE.ENR.PRIM.FM.ZS  209 non-null    float64
 10  SH.DYN.NCOM.ZS     209 non-null    float64
 11  SH.H2O.SMDW.ZS     209 non-null    float64
 12  SH.STA.SUIC.P5     209 non-null    float64
 13  SL.TLF.ACTI.FE.ZS  209 non-null    float64
 14  SL.TLF.CACT.ZS     209 non-null    float64
 15  SL.UEM.TOTL.NE.ZS  209 non-null    float64
 16  SP.DYN.AMRT.FE     209 non-nu

In [78]:
df8.loc[:,["AG.LND.AGRI.K2","BM.KLT.DINV.CD.WD","DT.DOD.DECT.CD","EN.POP.DNST","GB.XPD.RSDV.GD.ZS","IT.NET.USER.ZS","MS.MIL.XPND.CD","NE.CON.PRVT.PC.KD","SE.ENR.PRIM.FM.ZS","SH.DYN.NCOM.ZS","SH.H2O.SMDW.ZS","SH.STA.SUIC.P5","SL.TLF.ACTI.FE.ZS","SL.TLF.CACT.ZS","SL.UEM.TOTL.NE.ZS","SP.DYN.AMRT.FE","SP.DYN.AMRT.MA","SP.DYN.TFRT.IN","SP.POP.GROW"]]=[0.20751274913607134,0.08552420187258936,
                                                                    0.14169898559258015,0.13254239596390713,0.30034849332921804,0.5596704712643792,0.061591551205278115,0.4378254155402604,0.5565524599048634,0.3601674641148326,0.6828923964116737,0.2873977873977874,0.5377285128194529,0.4208988863621483,0.2616949427749984,0.15356974784213306, 0.3531083753872107,0.1933118369045143,0.5233753951870519]
df8


AG.LND.AGRI.K2  BM.KLT.DINV.CD.WD  DT.DOD.DECT.CD  EN.POP.DNST  \
economy                                                                   
BRA            0.207513           0.085524        0.141699     0.132542   
COL            0.207513           0.085524        0.141699     0.132542   
GEO            0.207513           0.085524        0.141699     0.132542   
GTM            0.207513           0.085524        0.141699     0.132542   
IRN            0.207513           0.085524        0.141699     0.132542   
KAZ            0.207513           0.085524        0.141699     0.132542   
KGZ            0.207513           0.085524        0.141699     0.132542   
MEX            0.207513           0.085524        0.141699     0.132542   
MNE            0.207513           0.085524        0.141699     0.132542   
MNG            0.207513           0.085524        0.141699     0.132542   
PAK            0.207513           0.085524        0.141699     0.132542   
PER            0.207513           0.085524        0.141699     0.132542   
ROU            0.207513           0.085524        0.141699     0.132542   
RWA            0.207513           0.085524        0.141699     0.132542   
SRB            0.207513           0.085524        0.141699     0.132542   
BLR            0.207513           0.085524        0.141699     0.132542   
BRA            0.207513           0.085524        0.141699     0.132542   
COL            0.207513           0.085524        0.141699     0.132542   
CRI            0.207513           0.085524        0.141699     0.132542   
GEO            0.207513           0.085524        0.141699     0.132542   
GMB            0.207513           0.085524        0.141699     0.132542   
GTM            0.207513           0.085524        0.141699     0.132542   
KAZ            0.207513           0.085524        0.141699     0.132542   
KGZ            0.207513           0.085524        0.141699     0.132542   
MEX            0.207513           0.085524        0.141699     0.132542   
MKD            0.207513           0.085524        0.141699     0.132542   
MNE            0.207513           0.085524        0.141699     0.132542   
MNG            0.207513           0.085524        0.141699     0.132542   
PER            0.207513           0.085524        0.141699     0.132542   
PHL            0.207513           0.085524        0.141699     0.132542   
ROU            0.207513           0.085524        0.141699     0.132542   
SRB            0.207513           0.085524        0.141699     0.132542   
TUN            0.207513           0.085524        0.141699     0.132542   
UZB            0.207513           0.085524        0.141699     0.132542   
BGR            0.207513           0.085524        0.141699     0.132542   
BLR            0.207513           0.085524        0.141699     0.132542   
BRA            0.207513           0.085524        0.141699     0.132542   
COL            0.207513           0.085524        0.141699     0.132542   
CRI            0.207513           0.085524        0.141699     0.132542   
GEO            0.207513           0.085524        0.141699     0.132542   
GTM            0.207513           0.085524        0.141699     0.132542   
IRN            0.207513           0.085524        0.141699     0.132542   
KAZ            0.207513           0.085524        0.141699     0.132542   
KGZ            0.207513           0.085524        0.141699     0.132542   
MDA            0.207513           0.085524        0.141699     0.132542   
MEX            0.207513           0.085524        0.141699     0.132542   
MKD            0.207513           0.085524        0.141699     0.132542   
MNE            0.207513           0.085524        0.141699     0.132542   
MNG            0.207513           0.085524        0.141699     0.132542   
PER            0.207513           0.085524        0.141699     0.132542   
ROU            0.207513           0.085524        0.141699     0.132542   
SRB            0.207513           

In [91]:
df9=pd.DataFrame(data=x_values)
df9
df9.to_csv("df9.csv")

In [83]:
df8.shape,df9.shape

((209, 20), (209, 19))

In [36]:
#df8は平均値配列、df9は実測値配列
Sensf(df8,df9)

          0  BM.KLT.DINV.CD.WD  DT.DOD.DECT.CD  EN.POP.DNST  \
economy                                                       
BRA     NaN           0.085524        0.141699     0.132542   
COL     NaN           0.085524        0.141699     0.132542   
GEO     NaN           0.085524        0.141699     0.132542   
GTM     NaN           0.085524        0.141699     0.132542   
IRN     NaN           0.085524        0.141699     0.132542   
KAZ     NaN           0.085524        0.141699     0.132542   
KGZ     NaN           0.085524        0.141699     0.132542   
MEX     NaN           0.085524        0.141699     0.132542   
MNE     NaN           0.085524        0.141699     0.132542   
MNG     NaN           0.085524        0.141699     0.132542   
PAK     NaN           0.085524        0.141699     0.132542   
PER     NaN           0.085524        0.141699     0.132542   
ROU     NaN           0.085524        0.141699     0.132542   
RWA     NaN           0.085524        0.141699     0.13

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [37]:
df8.info()

<class 'pandas.core.frame.DataFrame'>
Index: 209 entries, BRA to UKR
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   AG.LND.AGRI.K2     209 non-null    float64
 1   BM.KLT.DINV.CD.WD  209 non-null    float64
 2   DT.DOD.DECT.CD     209 non-null    float64
 3   EN.POP.DNST        209 non-null    float64
 4   GB.XPD.RSDV.GD.ZS  209 non-null    float64
 5   IT.NET.USER.ZS     209 non-null    float64
 6   MS.MIL.XPND.CD     209 non-null    float64
 7   NE.CON.PRVT.PC.KD  209 non-null    float64
 8   NY.GDP.PCAP.CD     209 non-null    float64
 9   SE.ENR.PRIM.FM.ZS  209 non-null    float64
 10  SH.DYN.NCOM.ZS     209 non-null    float64
 11  SH.H2O.SMDW.ZS     209 non-null    float64
 12  SH.STA.SUIC.P5     209 non-null    float64
 13  SL.TLF.ACTI.FE.ZS  209 non-null    float64
 14  SL.TLF.CACT.ZS     209 non-null    float64
 15  SL.UEM.TOTL.NE.ZS  209 non-null    float64
 16  SP.DYN.AMRT.FE     209 non-nu

In [38]:
df9.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209 entries, 0 to 208
Data columns (total 19 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       209 non-null    float64
 1   1       209 non-null    float64
 2   2       209 non-null    float64
 3   3       209 non-null    float64
 4   4       209 non-null    float64
 5   5       209 non-null    float64
 6   6       209 non-null    float64
 7   7       209 non-null    float64
 8   8       209 non-null    float64
 9   9       209 non-null    float64
 10  10      209 non-null    float64
 11  11      209 non-null    float64
 12  12      209 non-null    float64
 13  13      209 non-null    float64
 14  14      209 non-null    float64
 15  15      209 non-null    float64
 16  16      209 non-null    float64
 17  17      209 non-null    float64
 18  18      209 non-null    float64
dtypes: float64(19)
memory usage: 31.1 KB


In [92]:
df9

0         1         2         3         4         5         6   \
0    1.000000  0.301263  0.850459  0.046079  0.879138  0.900656  0.293220   
1    0.208655  0.085498  0.206548  0.085524  0.221528  0.789583  0.115079   
2    0.009048  0.054321  0.027057  0.124173  0.194069  0.837474  0.003516   
3    0.015316  0.055008  0.036457  0.300340  0.002493  0.532581  0.003756   
4    0.197685  0.051830  0.006241  0.096760  0.638424  0.948779  0.141800   
5    0.903213  0.027052  0.236993  0.010020  0.070707  1.000000  0.021830   
6    0.042836  0.051637  0.011621  0.062567  0.049747  0.614885  0.001459   
7    0.405137  0.116386  0.706308  0.125234  0.193446  0.852731  0.075275   
8    0.000108  0.051734  0.011458  0.087242  0.252385  0.895221  0.000879   
9    0.478104  0.052293  0.046363  0.000636  0.051632  0.615883  0.001129   
10   0.152512  0.049967  0.160540  0.547330  0.131954  0.191711  0.117578   
11   0.102460  0.046128  0.095174  0.046369  0.099234  0.726518  0.031316   
12   0.057447  0.072005  0.176110  0.161637  0.337738  0.897476  0.052212   
13   0.006678  0.050959  0.008726  1.000000  0.545206  0.303077  0.001404   
14   0.013736  0.054145  0.047726  0.152256  0.640709  0.944363  0.012946   
15   0.034742  0.051505  0.057021  0.087739  0.431304  0.965729  0.008033   
16   1.000000  0.073112  0.834132  0.045708  0.849208  0.857275  0.318919   
17   0.208160  0.107143  0.198071  0.084325  0.214584  0.778601  0.114707   
18   0.006554  0.057271  0.041450  0.188530  0.258440  0.895259  0.000000   
19   0.009055  0.054121  0.024914  0.124392  0.190982  0.761034  0.003779   
20   0.001579  0.050859  0.000000  0.438276  0.034292  0.385394  0.000130   
21   0.015316  0.052460  0.035319  0.295637  0.004689  0.496398  0.003091   
22   0.911925  0.000000  0.234030  0.009848  0.069535  0.962911  0.017797   
23   0.042846  0.050954  0.011186  0.061203  0.057842  0.512612  0.001439   
24   0.406869  0.183883  0.681526  0.123838  0.210711  0.799134  0.066093   
25   0.004363  0.050192  0.011947  0.157968  0.252675  0.966202  0.001354   
26   0.000107  0.052069  0.010990  0.087271  0.356598  0.870780  0.000893   
27   0.478356  0.051206  0.043575  0.000567  0.058242  0.566617  0.001087   
28   0.103391  0.042231  0.098950  0.045571  0.076969  0.665452  0.029978   
29   0.052325  0.096055  0.117206  0.697802  0.221921  0.528826  0.032173   
30   0.055706  0.067394  0.167498  0.162508  0.354654  0.860356  0.049336   
31   0.013757  0.054828  0.046095  0.153094  0.664629  0.893774  0.009255   
32   0.040014  0.051273  0.051428  0.142514  0.515863  0.779405  0.009555   
33   0.106863  0.050922  0.025528  0.143218  0.075225  0.667269  0.016303   
34   0.020275  0.056339  0.060347  0.124358  0.531851  0.769667  0.008150   
35   0.034915  0.051643  0.058243  0.087930  0.416228  0.907191  0.007081   
36   0.999999  0.285035  0.812057  0.045325  0.811970  0.820320  0.331193   
37   0.208190  0.091379  0.187296  0.082998  0.176567  0.755321  0.113387   
38   0.006542  0.053893  0.037327  0.186630  0.298823  0.871586  0.000000   
39   0.009100  0.053196  0.023563  0.124442  0.183348  0.723463  0.003635   
40   0.015316  0.051605  0.033807  0.290889  0.004778  0.451498  0.003113   
41   0.195242  0.051731  0.009181  0.094053  0.598863  0.777573  0.157677   
42   0.912676  0.061394  0.236980  0.009675  0.076835  0.932015  0.015739   
43   0.043561  0.050581  0.011136  0.059930  0.062293  0.455227  0.001375   
44   0.008814  0.051019  0.009405  0.184599  0.171113  0.928246  0.000350   
45   0.408687  0.084729  0.664043  0.122412  0.226447  0.775182  0.057294   
46   0.004372  0.052899  0.011764  0.157835  0.245790  0.908194  0.001140   
47   0.000105  0.051021  0.009780  0.087292  0.241776  0.867728  0.000744   
48   0.478500  0.051433  0.040842  0.000496  0.082422  0.274569  0.000990   
49   0.102628  0.066496  0.100200  0.044736  0.072517  0.608030  0.030172   
50   0.055554  0.055138  0.169685  0.163486  0.356212  0.773873  0.040995   
51   0.

In [40]:
list(range(18))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]

In [93]:
def Sensf3(df9):
    Sensitive_list=[]
    
    df8=pd.concat([df9.mean().to_frame().T]*len(df9)).reset_index(drop=True)
    
    for i in range(len(df8.columns)):
        tmp=df8.copy()
        tmp.iloc[:,i]=df9.iloc[:,i]
        
        data=tmp.values
        
        svr_out=svr.predict(data).reshape(-1,1)
        
        reg=LinearRegression().fit(df9.iloc[:,i].values.reshape(-1,1),svr_out)
        #モデルが変化したので感度も変化
        reg.coef_[0]
        Sensitive_list.append(reg.coef_[0])
    return Sensitive_list

In [94]:
Sensf3(df9)

[array([-0.09257115]),
 array([0.00353183]),
 array([0.20877395]),
 array([-0.07887478]),
 array([-0.18278549]),
 array([-0.05836288]),
 array([0.86182334]),
 array([0.81228395]),
 array([-0.07581322]),
 array([-0.34386729]),
 array([-0.16193827]),
 array([0.27927999]),
 array([0.10814728]),
 array([-0.02694151]),
 array([-0.06523548]),
 array([0.33442835]),
 array([0.04747051]),
 array([-0.15877202]),
 array([-0.28885799])]

In [46]:
def check_unit_root(df):
    """
    引数：df（単位根検定の対象となる列から構成される`DataFrame`）
    戻り値：検定の臨界値が1%，5%，10%の結果が含まれる３つの`DataFrame`からなる辞書
           行ラベルには`df`の列ラベルが使われている。
           列ラベルは検定を行う際の回帰式の種類を示す。
    """

    result = {}

    for val in ['1%','5%','10%']:
        df_result = pd.DataFrame(index=df.columns)

        for reg in ['nc','c',"ct"]:
            reg_list = []

            for col in df.columns:    
                res = adfuller(df[col], regression=reg)
                if res[0] <= res[4][val]:
                    reg_list.append( 'reject' )
                else:
                    reg_list.append( 'not' )
                    
            df_result[reg] = reg_list
        
        result[val] = df_result

    return result

In [49]:
result = check_unit_root(df9)

In [50]:
result["5%"]

nc       c      ct
0   not  reject  reject
1   not  reject  reject
2   not  reject  reject
3   not  reject  reject
4   not  reject  reject
5   not     not  reject
6   not  reject  reject
7   not  reject  reject
8   not  reject  reject
9   not  reject  reject
10  not  reject  reject
11  not  reject  reject
12  not  reject  reject
13  not  reject  reject
14  not  reject  reject
15  not  reject  reject
16  not  reject  reject
17  not  reject  reject
18  not  reject  reject

In [ ]:
#訓練データ(2009~2017)
train_dataY=df7.loc[:,"NY.GDP.PCAP.CD"]
train_y=train_dataY.values.reshape(-1,1)

#テストデータ
test_dataY=df10.loc[:,"NY.GDP.PCAP.CD"]
test_y=test_dataY.values.reshape(-1,1)

In [96]:
#訓練データ
train_dataX2=df7.drop(["NY.GDP.PCAP.CD","BM.KLT.DINV.CD.WD"],axis=1)
train_x2=train_dataX2.values

#テストデータ
test_dataX2=df10.drop(["NY.GDP.PCAP.CD","BM.KLT.DINV.CD.WD"],axis=1)
test_x2=test_dataX2.values

In [101]:
x_tr2=train_x2
y_tr=train_y

x_test2=test_x2
y_test=test_y

x_tr2=minmax_sc.fit_transform(x_tr2)
y_tr=minmax_sc.fit_transform(y_tr)
x_test2=minmax_sc.fit_transform(x_test2)
y_test=minmax_sc.fit_transform(y_test)

In [102]:
x_train,x_valid,y_train,y_valid=train_test_split(x_tr2,y_tr)

In [103]:
#交差検証法を用いたグリッドサーチ
best_score=0
best_parameters={}

param_list=[0.001,0.01,0.1,1,10,100]

for gamma in param_list:
    for C in param_list:
        for epsilon in param_list:
            svr=SVR(kernel="rbf",C=C,epsilon=epsilon,gamma=gamma)
            scores=cross_val_score(svr,x_tr2,y_tr,cv=5)
            score=np.mean(scores)
            
            if score > best_score:
                best_score=score
                best_parameters={"gamma":gamma,"C":C,"epsilon":epsilon}

svr=SVR(**best_parameters)
svr.fit(x_tr2,y_tr)
test_score=svr.score(x_test2,y_test)




/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when

/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when

/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when

/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when

/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when

/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when

/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when

/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when

/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/masudashinnosuke/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when

In [105]:
print(test_score)
print(best_parameters)

0.7176742135468643
{'gamma': 1, 'C': 10, 'epsilon': 0.01}
